/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ActivitiesRouteImport } from './routes/activities'
import { Route as ExteriorAngleRouteImport } from './routes/exterior-angle'
import { Route as InteriorAnglesRouteImport } from './routes/interior-angles'
import { Route as PracticeRouteImport } from './routes/practice'
import { Route as TriangleInequalityRouteImport } from './routes/triangle-inequality'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ActivitiesRoute = ActivitiesRouteImport.update({
  id: '/activities',
  path: '/activities',
  getParentRoute: () => rootRouteImport,
} as any)
const ExteriorAngleRoute = ExteriorAngleRouteImport.update({
  id: '/exterior-angle',
  path: '/exterior-angle',
  getParentRoute: () => rootRouteImport,
} as any)
const InteriorAnglesRoute = InteriorAnglesRouteImport.update({
  id: '/interior-angles',
  path: '/interior-angles',
  getParentRoute: () => rootRouteImport,
} as any)
const PracticeRoute = PracticeRouteImport.update({
  id: '/practice',
  path: '/practice',
  getParentRoute: () => rootRouteImport,
} as any)
const TriangleInequalityRoute = TriangleInequalityRouteImport.update({
  id: '/triangle-inequality',
  path: '/triangle-inequality',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/activities': typeof ActivitiesRoute
  '/exterior-angle': typeof ExteriorAngleRoute
  '/interior-angles': typeof InteriorAnglesRoute
  '/practice': typeof PracticeRoute
  '/triangle-inequality': typeof TriangleInequalityRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/activities': typeof ActivitiesRoute
  '/exterior-angle': typeof ExteriorAngleRoute
  '/interior-angles': typeof InteriorAnglesRoute
  '/practice': typeof PracticeRoute
  '/triangle-inequality': typeof TriangleInequalityRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/activities': typeof ActivitiesRoute
  '/exterior-angle': typeof ExteriorAngleRoute
  '/interior-angles': typeof InteriorAnglesRoute
  '/practice': typeof PracticeRoute
  '/triangle-inequality': typeof TriangleInequalityRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/activities'
    | '/exterior-angle'
    | '/interior-angles'
    | '/practice'
    | '/triangle-inequality'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/activities'
    | '/exterior-angle'
    | '/interior-angles'
    | '/practice'
    | '/triangle-inequality'
  id:
    | '__root__'
    | '/'
    | '/activities'
    | '/exterior-angle'
    | '/interior-angles'
    | '/practice'
    | '/triangle-inequality'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ActivitiesRoute: typeof ActivitiesRoute
  ExteriorAngleRoute: typeof ExteriorAngleRoute
  InteriorAnglesRoute: typeof InteriorAnglesRoute
  PracticeRoute: typeof PracticeRoute
  TriangleInequalityRoute: typeof TriangleInequalityRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/activities': {
      id: '/activities'
      path: '/activities'
      fullPath: '/activities'
      preLoaderRoute: typeof ActivitiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exterior-angle': {
      id: '/exterior-angle'
      path: '/exterior-angle'
      fullPath: '/exterior-angle'
      preLoaderRoute: typeof ExteriorAngleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/interior-angles': {
      id: '/interior-angles'
      path: '/interior-angles'
      fullPath: '/interior-angles'
      preLoaderRoute: typeof InteriorAnglesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/practice': {
      id: '/practice'
      path: '/practice'
      fullPath: '/practice'
      preLoaderRoute: typeof PracticeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/triangle-inequality': {
      id: '/triangle-inequality'
      path: '/triangle-inequality'
      fullPath: '/triangle-inequality'
      preLoaderRoute: typeof TriangleInequalityRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ActivitiesRoute: ActivitiesRoute,
  ExteriorAngleRoute: ExteriorAngleRoute,
  InteriorAnglesRoute: InteriorAnglesRoute,
  PracticeRoute: PracticeRoute,
  TriangleInequalityRoute: TriangleInequalityRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
